
import fs from "node:fs";
import assert from "node:assert/strict";
import vm from "node:vm";
import { DatabaseSync } from "node:sqlite";
import worker from "../dist/server/index.js";
const sql=new DatabaseSync(":memory:");
sql.exec(fs.readFileSync("drizzle/0000_omniscient_midnight.sql","utf8"));
const DB={prepare(q){const stmt=sql.prepare(q);let values=[];return {bind(...args){values=args;return this},async all(){return {results:stmt.all(...values)}},async first(){return stmt.get(...values)||null},async run(){stmt.run(...values);return {success:true}}}},async batch(items){sql.exec("BEGIN");try{const r=[];for(const s of items)r.push(await s.run());sql.exec("COMMIT");return r}catch(e){sql.exec("ROLLBACK");throw e}}};
const blobs=new Map();
const BUCKET={async put(k,b){blobs.set(k,new Uint8Array(b))},async get(k){const b=blobs.get(k);return b?{body:b,arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)}:null},async delete(k){blobs.delete(k)}};
const env={DB,BUCKET};
const call=(path,options={})=>worker.fetch(new Request("https://local.test"+path,{...options,headers:{"oai-authenticated-user-id":"test-owner",origin:"https://local.test",...options.headers}}),env,{});
assert.equal((await worker.fetch(new Request("https://local.test/api/library"),env,{})).status,401);
assert.equal((await call("/api/tags",{method:"POST",headers:{origin:"https://other.test"},body:"{}"})).status,403);
const original=fs.readFileSync("public/assets/characters.png");
const form=new FormData();form.append("file",new File([original],"原图.png",{type:"image/png"}));form.append("preview",new File([new Uint8Array([255,216,255,224,0,0])],"preview.jpg",{type:"image/jpeg"}));form.append("projectId","PRJ-001");form.append("name","测试素材");
const upload=await call("/api/assets",{method:"POST",body:form});assert.equal(upload.status,201);const {role}=await upload.json();
let download=await call(role.downloadUrl);assert.equal(download.status,200);assert.deepEqual(Buffer.from(await download.arrayBuffer()),original);assert(download.headers.get("content-disposition").includes("UTF-8"));
const patch={revision:1,name:"手动标签角色",description:"用户自己维护",tags:[{dimension:"age",name:"儿童"},{dimension:"gender",name:"女性"},{dimension:"era",name:"民国"},{dimension:"style",name:"自定义绘画"},{dimension:"style",name:"水彩"}]};
let save=await call("/api/assets/"+role.id,{method:"PATCH",body:JSON.stringify(patch)});assert.equal(save.status,200);const updated=(await save.json()).role;
assert.equal(updated.classification.age,"儿童");assert.equal(updated.tags.length,5);
assert.equal((await call("/api/assets/"+role.id,{method:"PATCH",body:JSON.stringify(patch)})).status,409);
const add=await call("/api/tags",{method:"POST",body:JSON.stringify({dimension:"era",name:"架空民国"})});assert.equal(add.status,201);
await call("/api/tags",{method:"POST",body:JSON.stringify({dimension:"style",name:"自定义绘画"})});
let library=await (await call("/api/library")).json();assert.equal(library.roles.length,1);assert.equal(library.labels.filter(t=>t.name==="自定义绘画").length,1);
assert.equal((await call("/api/assets/"+role.id+"/analyze",{method:"POST",body:"{}"})).status,404);
const bad=new FormData();bad.append("file",new File(["not an image"],"bad.png",{type:"image/png"}));assert.equal((await call("/api/assets",{method:"POST",body:bad})).status,400);
assert.equal((await worker.fetch(new Request("https://local.test/"),env,{})).status,200);
const elements=new Map();
const el=s=>{if(!elements.has(s))elements.set(s,{style:{},dataset:{},innerHTML:"",textContent:"",value:"",hidden:false,open:false,disabled:false,classList:{toggle(){}},setAttribute(){},addEventListener(){},insertAdjacentHTML(){},reset(){},focus(){},showModal(){this.open=true},close(){this.open=false}});return elements.get(s)};
const document={querySelector:el,querySelectorAll:()=>[],addEventListener(){},activeElement:{tagName:"BODY"},body:el("body")};
const context=vm.createContext({document,window:{addEventListener(){}},structuredClone,console,FormData,fetch:async()=>new Response(JSON.stringify(library)),AbortController});
const source=["data.js","app.js","manage.js"].map(f=>fs.readFileSync("public/"+f,"utf8")).join("\n");
vm.runInContext(source,context);await new Promise(r=>setTimeout(r,20));
const run=s=>vm.runInContext(s,context);
assert.equal(run("taxonomy.length"),10);
run('state.filters={age:"儿童",era:"民国"};update()');assert.equal(run("matchRoles().length"),1);
run('detail(roles.find(r=>!r.sample).id)');assert(el("#detail-content").innerHTML.includes("下载原图"));assert(el("#detail-content").innerHTML.includes("儿童"));
el('#edit-dimension').value='style';run('editor()');assert(el("#edit-dialog").open);
for(const f of ["worker/index.js","public/manage.js","dist/server/index.js"])assert(!fs.readFileSync(f,"utf8").includes("api.openai.com"));
console.log("PASS: upload, exact original download, persistent labels, deduplication, revision conflict, auth, origin, removed endpoint, 10 dimensions, combined filters, details, editor.");
sql.close();
